import type { Character } from '~/types/character'

export const characters: Character[] = [
  // Wind Breaker
  { id: 'wb-1', name: '櫻遙', series: 'WindBreaker', image: 'images/防風少年/櫻遙.jpeg' },
  { id: 'wb-2', name: '梅宮一', series: 'WindBreaker', image: 'images/防風少年/梅宮一.jpg' },
  { id: 'wb-3', name: '蘇枋隼飛', series: 'WindBreaker', image: 'images/防風少年/蘇枋隼飛.jpg' },
  { id: 'wb-4', name: '杉下京太郎', series: 'WindBreaker', image: 'images/防風少年/杉下京太郎.jpg' },
  { id: 'wb-5', name: '兔耳山丁子', series: 'WindBreaker', image: 'images/防風少年/兔耳山丁子.jpg' },
  { id: 'wb-6', name: '桐生三輝', series: 'WindBreaker', image: 'images/防風少年/桐生三輝.jpg' },
  { id: 'wb-7', name: '梶蓮', series: 'WindBreaker', image: 'images/防風少年/梶蓮.jpg' },
  { id: 'wb-8', name: '十亀条', series: 'WindBreaker', image: 'images/防風少年/十亀条.jpg' },

  // Haikyu
  { id: 'hq-1', name: '日向翔陽', series: 'Haikyu', image: 'images/排球少年/日向翔陽.jpg' },
  { id: 'hq-2', name: '影山飛雄', series: 'Haikyu', image: 'images/排球少年/影山飛雄.jpg' },
  { id: 'hq-3', name: '及川徹', series: 'Haikyu', image: 'images/排球少年/及川徹.jpg' },
  { id: 'hq-4', name: '黑尾鐵朗', series: 'Haikyu', image: 'images/排球少年/黑尾鐵朗.jpg' },
  { id: 'hq-5', name: '孤爪研磨', series: 'Haikyu', image: 'images/排球少年/孤爪研磨.jpg' },
  { id: 'hq-6', name: '木兎光太郎', series: 'Haikyu', image: 'images/排球少年/木兎光太郎.webp' },
  { id: 'hq-7', name: '赤葦京治', series: 'Haikyu', image: 'images/排球少年/赤葦京治.jpg' },
  { id: 'hq-8', name: '宮侑', series: 'Haikyu', image: 'images/排球少年/宮侑.jpg' },
  { id: 'hq-9', name: '宮治', series: 'Haikyu', image: 'images/排球少年/宮治.jpg' },
  { id: 'hq-10', name: '北信介', series: 'Haikyu', image: 'images/排球少年/北信介.jpg' },
  { id: 'hq-11', name: '角名倫太郎', series: 'Haikyu', image: 'images/排球少年/角名倫太郎.jpg' },
  { id: 'hq-12', name: '菅原孝支', series: 'Haikyu', image: 'images/排球少年/菅原孝支.jpg' },
  { id: 'hq-13', name: '澤村大地', series: 'Haikyu', image: 'images/排球少年/澤村大地.jpg' },
  { id: 'hq-14', name: '貓又育史', series: 'Haikyu', image: 'images/排球少年/貓又育史.jpg' },
  { id: 'hq-15', name: '牛島若利', series: 'Haikyu', image: 'images/排球少年/牛島若利.jpg' },
  { id: 'hq-16', name: '月島蛍', series: 'Haikyu', image: 'images/排球少年/月島蛍.jpg' },
  { id: 'hq-17', name: '照島遊兒', series: 'Haikyu', image: 'images/排球少年/照島遊兒.jpg' },
  { id: 'hq-18', name: '天童覺', series: 'Haikyu', image: 'images/排球少年/天童覺.jpg' },
  { id: 'hq-19', name: '國見英', series: 'Haikyu', image: 'images/排球少年/國見英.jpg' },
  { id: 'hq-20', name: '夜久衛輔', series: 'Haikyu', image: 'images/排球少年/夜久衛輔.jpg' },
  { id: 'hq-21', name: '灰羽利耶夫', series: 'Haikyu', image: 'images/排球少年/灰羽利耶夫.jpg' },
  { id: 'hq-22', name: '西谷夕', series: 'Haikyu', image: 'images/排球少年/西谷夕.jpg' },
  { id: 'hq-23', name: '古森元也', series: 'Haikyu', image: 'images/排球少年/古森元也.jpg' },
  { id: 'hq-24', name: '佐久早聖臣', series: 'Haikyu', image: 'images/排球少年/佐久早聖臣.jpg' },
  { id: 'hq-25', name: '白布賢二郎', series: 'Haikyu', image: 'images/排球少年/白布賢二郎.jpg' },
  { id: 'hq-26', name: '昼神幸郎', series: 'Haikyu', image: 'images/排球少年/昼神幸郎.jpg' },
  { id: 'hq-27', name: '瀨見英太', series: 'Haikyu', image: 'images/排球少年/瀨見英太.jpg'},

  // MHA
  { id: 'mha-1', name: '綠谷出久', series: 'MHA', image: 'images/我的英雄學院/綠谷出久.jpg' },
  { id: 'mha-2', name: '爆豪勝己', series: 'MHA', image: 'images/我的英雄學院/爆豪勝己.jpg' },
  { id: 'mha-3', name: '轟焦凍', series: 'MHA', image: 'images/我的英雄學院/轟焦凍.jpg' },
  { id: 'mha-4', name: '根津校長', series: 'MHA', image: 'images/我的英雄學院/根津校長.jpg' },
  { id: 'mha-5', name: '常闇踏陰', series: 'MHA', image: 'images/我的英雄學院/常闇踏陰.jpg' },
  { id: 'mha-6', name: '上鳴電氣', series: 'MHA', image: 'images/我的英雄學院/上鳴電氣.jpg' },
  { id: 'mha-7', name: '相澤消太', series: 'MHA', image: 'images/我的英雄學院/相澤消太.jpg' },
  { id: 'mha-8', name: '霍克斯', series: 'MHA', image: 'images/我的英雄學院/霍克斯.jpg' },
  { id: 'mha-9', name: '物間寧人', series: 'MHA', image: 'images/我的英雄學院/物間寧人.jpg' },
  { id: 'mha-10', name: '心操人使', series: 'MHA', image: 'images/我的英雄學院/心操人使.jpg' },
  { id: 'mha-11', name: '轟燈矢（荼毘）', series: 'MHA', image: 'images/我的英雄學院/轟燈矢.jpg' },
  { id: 'mha-12', name: '渡我被身子', series: 'MHA', image: 'images/我的英雄學院/渡我被身子.jpg' },
  { id: 'mha-13', name: '志村轉弧（死柄木弔）', series: 'MHA', image: 'images/我的英雄學院/志村轉弧.jpg' },
  { id: 'mha-14', name: '天喰環', series: 'MHA', image: 'images/我的英雄學院/天喰環.jpg' },
  { id: 'mha-15', name: '通形未吏生', series: 'MHA', image: 'images/我的英雄學院/通形未吏生.jpg' },
  { id: 'mha-16', name: '波動捻麗', series: 'MHA', image: 'images/我的英雄學院/波動捻麗.jpg' },
  { id: 'mha-17', name: '分倍河原仁', series: 'MHA', image: 'images/我的英雄學院/分倍河原仁.jpg' },
  { id: 'mha-18', name: '葉隱透', series: 'MHA', image: 'images/我的英雄學院/葉隱透.jpg' },
  { id: 'mha-19', name: '夜嵐稻佐', series: 'MHA', image: 'images/我的英雄學院/夜嵐稻佐.jpg' },
  { id: 'mha-20', name: '真堂搖', series: 'MHA', image: 'images/我的英雄學院/真堂搖.jpg'},
  { id: 'mha-21', name: '米爾科', series: 'MHA', image: 'images/我的英雄學院/米爾科.jpg' },
  { id: 'mha-22', name: '白雲朧（黑霧）', series: 'MHA', image: 'images/我的英雄學院/白雲朧.jpg' },
  { id: 'mha-23', name: '迫壓紘（壓縮先生）', series: 'MHA', image: 'images/我的英雄學院/迫壓紘.jpg' },
  { id: 'mha-24', name: '治崎廻', series: 'MHA', image: 'images/我的英雄學院/治崎廻.jpg' },
  // { id: 'mha-25', name: '塚內直正', series: 'MHA', image: 'images/我的英雄學院/塚內直正.jpg' },
  // { id: 'mha-26', name: '轟炎司', series: 'MHA', image: 'images/我的英雄學院/轟炎司.jpg' },
  { id: 'mha-27', name: '壞理', series: 'MHA', image: 'images/我的英雄學院/壞理.jpg' },
]
